name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"
        default: "0.0.0"
        required: true

jobs:
  iOS:
    name: Build iOS IPA
    runs-on: macos-latest
    environment: Build
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Setup Certificates
      uses: apple-actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
        keychain: github-actions-xamarin
        keychain-password: ""

    - name: Setup Provisioning Profiles
      uses: apple-actions/download-provisioning-profiles@v1
      with:
        bundle-id: 'com.julian-baumann.intershare-mobile'
        profile-type: 'IOS_APP_ADHOC'
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

    - name: Restore
      run: |
        dotnet restore src/InterShareMobile/InterShareMobile.csproj
        nuget restore src/InterShareMobile.iOS/InterShareMobile.iOS.csproj

    - name: Get Previous tag
      id: latest_tag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 0.0.0

    - name: Set iOS version
      run: |
        /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${{ github.event.inputs.version }}" src/InterShareMobile.iOS/Info.plist
        /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${{ github.run_number }}" src/InterShareMobile.iOS/Info.plist

    - name: Build iOS
      run: MSBuild /t:Build /p:Configuration=Release /p:Platform=iPhone /p:BuildIpa=true src/InterShareMobile.iOS/InterShareMobile.iOS.csproj

    - name: Rename IPA
      run: mv ${{ github.workspace }}/src/InterShareMobile.iOS/bin/iPhone/Release/InterShareMobile.iOS.ipa ${{ github.workspace }}/src/InterShareMobile.iOS/InterShare-${{ github.event.inputs.version }}.ipa

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: iOS-IPA
        path: ${{ github.workspace }}/src/InterShareMobile.iOS/InterShare-${{ github.event.inputs.version }}.ipa

  android:
    name: Build Android APK
    runs-on: macos-latest
    environment: Build
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore
      run: |
        dotnet restore src/InterShareMobile/InterShareMobile.csproj
        nuget restore src/InterShareMobile.Android/InterShareMobile.Android.csproj

    - name: Setup Android signing
      run: (echo -n ${{ secrets.ANDROID_KEYSTORE }} | base64 --decode) > src/InterShareMobile.Android/InterShare.jks

    - name: Get Previous tag
      id: latest_tag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 0.0.0

    - name: Set Android version
      uses: damienaicheh/update-android-version-manifest-action@v1.0.0
      with:
        android-manifest-path: src/InterShareMobile.Android/Properties/AndroidManifest.xml
        version-name: ${{ github.event.inputs.version }}
        version-code: ${{ github.run_number }}

    - name: Build Android
      run: MSBuild /t:SignAndroidPackage /p:Configuration=Release /p:AndroidPackageFormat=apk /p:AndroidKeyStore=true /p:AndroidSigningKeyAlias=intershare /p:AndroidSigningKeyPass=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} /p:AndroidSigningKeyStore=InterShare.jks /p:AndroidSigningStorePass=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} src/InterShareMobile.Android/InterShareMobile.Android.csproj

    - name: Rename APK
      run: mv ${{ github.workspace }}/src/InterShareMobile.Android/bin/Release/com.julian_baumann.intershare-Signed.apk ${{ github.workspace }}/src/InterShareMobile.Android/InterShare-${{ github.event.inputs.version }}.apk

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Android-APK
        path: ${{ github.workspace }}/src/InterShareMobile.Android/InterShare-${{ github.event.inputs.version }}.apk

  create-release:
    runs-on: macos-latest
    name: Create Release
    needs: [iOS, android]
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: ${{ github.workspace }}/downloads

    - name: Create Release strings
      id: release_strings
      run: |
        echo "RELEASE_TAG=${{ github.event.inputs.version }}" >> $GITHUB_ENV
        echo "RELEASE_NAME=Version ${{ github.event.inputs.version }}" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        name: ${{ env.RELEASE_NAME }}
        files: |
          ${{ github.workspace }}/downloads/Android-APK/InterShare-${{ github.event.inputs.version }}.apk
          ${{ github.workspace }}/downloads/iOS-IPA/InterShare-${{ github.event.inputs.version }}.ipa

  upload-app-store:
    runs-on: macos-latest
    name: Upload iOS app to App Store Connect
    needs: [create-release]
    environment: Build
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: ${{ github.workspace }}/downloads

    - name: Upload app to TestFlight
      uses: apple-actions/upload-testflight-build@v1
      with:
        app-path: ${{ github.workspace }}/downloads/iOS-IPA/InterShare-${{ github.event.inputs.version }}.ipa
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}